apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing-api
  name: testing-api
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30800
  selector:
    app: testing-api
status:
  loadBalancer: {}